name: Hello World Action

on: 
  push:
    branches:
      - main
#hey      what 1 2
concurrency:
  group: cd-researchPortal
  cancel-in-progress: true
  
jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: |
          echo "Hello, World!"
          sleep 60  # Sleep for 1 minute
