name: Upload to S3

on:
  workflow_dispatch  # Allows manual trigger from GitHub UI

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required to read repo contents

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::837491041518:role/Github-VultaraRepo
          role-session-name: test-${{ github.actor }}-${{ github.run_id }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Create a file
        run: echo "Hello, S3! This is a test file." > file.txt

      - name: Upload file to S3
        run: aws s3 cp file.txt s3://vultara-artifacts/
